In [55]:
!pip install pandas numpy matplotlib seaborn yfinance

Requirement already satisfied: pandas in c:\users\dell\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: numpy in c:\users\dell\anaconda3\lib\site-packages (2.1.3)
Requirement already satisfied: matplotlib in c:\users\dell\anaconda3\lib\site-packages (3.10.0)
Requirement already satisfied: seaborn in c:\users\dell\anaconda3\lib\site-packages (0.13.2)
Requirement already satisfied: yfinance in c:\users\dell\anaconda3\lib\site-packages (1.2.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dell\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\dell\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\dell\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\dell\anaconda3\lib\site-packages (from matplotlib) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\dell\anaconda3\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\dell\anaconda3\lib\site-packages (from matplotlib) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\dell\anaconda3\lib\site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\dell\anaconda3\lib\site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in c:\users\dell\anaconda3\lib\site-packages (from matplotlib) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\dell\anaconda3\lib\site-packages (from matplotlib) (3.2.0)
Requirement already satisfied: requests>=2.31 in c:\users\dell\anaconda3\lib\site-packages (from yfinance) (2.32.3)
Requirement already satisfied: multitasking>=0.0.7 in c:\users\dell\anaconda3\lib\site-packages (from yfinance) (0.0.12)
Requirement already satisfied: platformdirs>=2.0.0 in c:\users\dell\anaconda3\lib\site-packages (from yfinance) (4.3.7)
Requirement already satisfied: frozendict>=2.3.4 in c:\users\dell\anaconda3\lib\site-packages (from yfinance) (2.4.2)
Requirement already satisfied: peewee>=3.16.2 in c:\users\dell\anaconda3\lib\site-packages (from yfinance) (4.0.1)
Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\users\dell\anaconda3\lib\site-packages (from yfinance) (4.12.3)
Requirement already satisfied: curl_cffi<0.14,>=0.7 in c:\users\dell\anaconda3\lib\site-packages (from yfinance) (0.13.0)
Requirement already satisfied: protobuf>=3.19.0 in c:\users\dell\anaconda3\lib\site-packages (from yfinance) (5.29.3)
Requirement already satisfied: websockets>=13.0 in c:\users\dell\anaconda3\lib\site-packages (from yfinance) (16.0)
Requirement already satisfied: cffi>=1.12.0 in c:\users\dell\anaconda3\lib\site-packages (from curl_cffi<0.14,>=0.7->yfinance) (1.17.1)
Requirement already satisfied: certifi>=2024.2.2 in c:\users\dell\anaconda3\lib\site-packages (from curl_cffi<0.14,>=0.7->yfinance) (2025.4.26)
Requirement already satisfied: soupsieve>1.2 in c:\users\dell\anaconda3\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.5)
Requirement already satisfied: pycparser in c:\users\dell\anaconda3\lib\site-packages (from cffi>=1.12.0->curl_cffi<0.14,>=0.7->yfinance) (2.21)
Requirement already satisfied: six>=1.5 in c:\users\dell\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\dell\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\dell\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\dell\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (2.3.0)

In [56]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import yfinance as yf

In [57]:
assets = ["AAPL","MSFT","TSLA","AMZN","NVDA"]

data = pd.DataFrame()

for stock in assets:
    df = yf.download(stock, start="2020-01-01")
    data[stock] = df["Close"]

data = data.dropna()

data.head()

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

                 AAPL        MSFT       TSLA       AMZN      NVDA
Date
2020-01-02  72.400520  152.158386  28.684000  94.900497  5.970754
2020-01-03  71.696648  150.263779  29.534000  93.748497  5.875185
2020-01-06  72.267921  150.652161  30.102667  95.143997  5.899825
2020-01-07  71.928047  149.278595  31.270666  95.343002  5.971251
2020-01-08  73.085098  151.656326  32.809334  94.598503  5.982451

In [58]:
prices.to_csv("../data/market_prices.csv")

In [59]:
returns = prices.pct_change(fill_method=None)
returns = returns.dropna()

returns.head()

Ticker          AAPL      AMZN      MSFT      NVDA      TSLA
Date
2020-01-03 -0.009722 -0.012139 -0.012452 -0.016006  0.029633
2020-01-06  0.007968  0.014886  0.002585  0.004194  0.019255
2020-01-07 -0.004703  0.002092 -0.009118  0.012106  0.038801
2020-01-08  0.016086 -0.007809  0.015928  0.001876  0.049205
2020-01-09  0.021241  0.004799  0.012493  0.010983 -0.021945

In [60]:
returns.shape

(1556, 5)

In [61]:
prices.head()

Ticker           AAPL       AMZN        MSFT      NVDA       TSLA
Date
2020-01-02  72.400536  94.900497  152.158401  5.970755  28.684000
2020-01-03  71.696632  93.748497  150.263733  5.875186  29.534000
2020-01-06  72.267937  95.143997  150.652176  5.899826  30.102667
2020-01-07  71.928055  95.343002  149.278580  5.971251  31.270666
2020-01-08  73.085106  94.598503  151.656281  5.982451  32.809334

In [62]:
import yfinance as yf

assets = ["AAPL","MSFT","TSLA","AMZN","NVDA"]

data = yf.download(assets, start="2020-01-01")

prices = data["Close"]

prices.head()

[*********************100%***********************]  5 of 5 completed

Ticker           AAPL       AMZN        MSFT      NVDA       TSLA
Date
2020-01-02  72.400513  94.900497  152.158386  5.970754  28.684000
2020-01-03  71.696648  93.748497  150.263748  5.875187  29.534000
2020-01-06  72.267944  95.143997  150.652130  5.899826  30.102667
2020-01-07  71.928055  95.343002  149.278534  5.971253  31.270666
2020-01-08  73.085121  94.598503  151.656296  5.982452  32.809334

In [63]:
prices.shape

(1557, 5)

In [64]:
returns = prices.pct_change()
returns = returns.dropna()

returns.head()

Ticker          AAPL      AMZN      MSFT      NVDA      TSLA
Date
2020-01-03 -0.009722 -0.012139 -0.012452 -0.016006  0.029633
2020-01-06  0.007968  0.014886  0.002585  0.004194  0.019255
2020-01-07 -0.004703  0.002092 -0.009118  0.012107  0.038801
2020-01-08  0.016086 -0.007809  0.015928  0.001876  0.049205
2020-01-09  0.021241  0.004799  0.012493  0.010983 -0.021945

In [65]:
returns.shape

(1556, 5)

In [66]:
weights = [0.2,0.2,0.2,0.2,0.2]

portfolio_returns = returns.dot(weights)

portfolio_returns.head()

Date
2020-01-03   -0.004137
2020-01-06    0.009777
2020-01-07    0.007836
2020-01-08    0.015057
2020-01-09    0.005514
dtype: float64

In [67]:
returns.shape

(1556, 5)

In [68]:
returns.to_csv("../data/market_returns.csv")

In [69]:
import numpy as np
weights = np.array([0.2,0.2,0.2,0.2,0.2,])

In [70]:
portfolio_returns = returns.dot(weights)
portfolio_returns.head()

Date
2020-01-03   -0.004137
2020-01-06    0.009777
2020-01-07    0.007836
2020-01-08    0.015057
2020-01-09    0.005514
dtype: float64

In [71]:
portfolio_returns.to_csv("../data/portfolio_returns.csv")

In [72]:
portfolio_volatility = portfolio_returns.std()
portfolio_volatility

0.02164152700044273

In [73]:
annual_volatility = portfolio_volatility * np.sqrt(252)
annual_volatility

np.float64(0.34354859060916654)

In [74]:
VaR_95 = portfolio_returns.quantile(0.05)
VaR_95

np.float64(-0.03353997983853055)

In [75]:
risk_free_rate = 0.02 / 252

sharpe_ratio = (portfolio_returns.mean() - risk_free_rate) / portfolio_returns.std()

sharpe_ratio

np.float64(0.06854717635045866)

In [76]:
correlation_matrix = returns.corr()
correlation_matrix

Ticker      AAPL      AMZN      MSFT      NVDA      TSLA
Ticker
AAPL    1.000000  0.578853  0.687525  0.573440  0.484710
AMZN    0.578853  1.000000  0.653121  0.569042  0.444502
MSFT    0.687525  0.653121  1.000000  0.662659  0.444163
NVDA    0.573440  0.569042  0.662659  1.000000  0.475673
TSLA    0.484710  0.444502  0.444163  0.475673  1.000000

In [77]:
correlation_matrix.to_csv("../data/correlation_matrix.csv")